<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INSUPLTQAPT" failures="1" tests="1" name="testcases.NewCustomerCreation" time="0.438" errors="0" timestamp="2024-10-13T17:04:46 IST" skipped="0">
  <testcase classname="testcases.NewCustomerCreation" name="addCustomer" time="0.438">
    <failure message="Failing new customer test focefully" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing new customer test focefully
at org.testng.Assert.fail(Assert.java:111)
at testcases.NewCustomerCreation.addCustomer(NewCustomerCreation.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[Capturing screenshot for failed cases
<a target="_blank" href="C:\Users\pthakare\Selenium Testing\Images\error.jpg">Screenshot</a>
<br>
<a target="_blank" href="C:\Users\pthakare\Selenium Testing\Images\error.jpg"><img src="C:\Users\pthakare\Selenium Testing\Images\error.jpg" height=200 width=200></img></a>]]>
    </system-out>
  </testcase> <!-- addCustomer -->
  <system-out>
    <![CDATA[Capturing screenshot for failed cases
<a target="_blank" href="C:\Users\pthakare\Selenium Testing\Images\error.jpg">Screenshot</a>
<br>
<a target="_blank" href="C:\Users\pthakare\Selenium Testing\Images\error.jpg"><img src="C:\Users\pthakare\Selenium Testing\Images\error.jpg" height=200 width=200></img></a>
Capturing screenshot for failed cases
<a target="_blank" href="C:\Users\pthakare\Selenium Testing\Images\error.jpg">Screenshot</a>
<br>
<a target="_blank" href="C:\Users\pthakare\Selenium Testing\Images\error.jpg"><img src="C:\Users\pthakare\Selenium Testing\Images\error.jpg" height=200 width=200></img></a>]]>
  </system-out>
</testsuite> <!-- testcases.NewCustomerCreation -->
