<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Capturing screenshot for failed cases]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="C:\Users\pthakare\Selenium Testing\Images\error.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="C:\Users\pthakare\Selenium Testing\Images\error.jpg"><img src="C:\Users\pthakare\Selenium Testing\Images\error.jpg" height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[Capturing screenshot for failed cases]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="C:\Users\pthakare\Selenium Testing\Images\error.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="C:\Users\pthakare\Selenium Testing\Images\error.jpg"><img src="C:\Users\pthakare\Selenium Testing\Images\error.jpg" height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite started-at="2024-10-13T17:04:45 IST" name="Data Driven Basics" finished-at="2024-10-13T17:04:46 IST" duration-ms="698">
    <groups>
    </groups>
    <test started-at="2024-10-13T17:04:45 IST" name="BankManagerLogin" finished-at="2024-10-13T17:04:46 IST" duration-ms="216">
      <class name="testcases.BankManagerLogin">
        <test-method signature="loginAsBankManager()[pri:0, instance:testcases.BankManagerLogin@5cf87cfd]" started-at="2024-10-13T17:04:45 IST" name="loginAsBankManager" finished-at="2024-10-13T17:04:46 IST" duration-ms="172" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing login test focefully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing login test focefully
at org.testng.Assert.fail(Assert.java:111)
at testcases.BankManagerLogin.loginAsBankManager(BankManagerLogin.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Capturing screenshot for failed cases]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="C:\Users\pthakare\Selenium Testing\Images\error.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="C:\Users\pthakare\Selenium Testing\Images\error.jpg"><img src="C:\Users\pthakare\Selenium Testing\Images\error.jpg" height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- testcases.BankManagerLogin -->
    </test> <!-- BankManagerLogin -->
    <test started-at="2024-10-13T17:04:46 IST" name="NewCustomerCreation" finished-at="2024-10-13T17:04:46 IST" duration-ms="455">
      <class name="testcases.NewCustomerCreation">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.NewCustomerCreation@6f667ad1]" started-at="2024-10-13T17:04:42 IST" name="setUp" finished-at="2024-10-13T17:04:45 IST" duration-ms="3150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addCustomer(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testcases.NewCustomerCreation@6f667ad1]" started-at="2024-10-13T17:04:46 IST" name="addCustomer" data-provider="getData" finished-at="2024-10-13T17:04:46 IST" duration-ms="438" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Vaibhav]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Patil]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[421302.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing new customer test focefully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing new customer test focefully
at org.testng.Assert.fail(Assert.java:111)
at testcases.NewCustomerCreation.addCustomer(NewCustomerCreation.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Capturing screenshot for failed cases]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="C:\Users\pthakare\Selenium Testing\Images\error.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="C:\Users\pthakare\Selenium Testing\Images\error.jpg"><img src="C:\Users\pthakare\Selenium Testing\Images\error.jpg" height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.NewCustomerCreation@6f667ad1]" started-at="2024-10-13T17:04:46 IST" name="tearDown" finished-at="2024-10-13T17:04:46 IST" duration-ms="165" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.NewCustomerCreation -->
    </test> <!-- NewCustomerCreation -->
  </suite> <!-- Data Driven Basics -->
</testng-results>
